name: filegram
version: 2.5.7+83
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  flutter_dotenv: ^5.0.2
  firebase_analytics: ^9.2.0
  get_storage: ^2.0.3
  cloud_firestore: ^3.3.0
  google_mobile_ads: ^1.3.0
  open_as_default: ^0.0.3
  flutter_file_dialog: ^2.3.0
  receive_sharing_intent: ^1.4.5
  lottie: ^1.3.0
  intl: ^0.17.0
  firebase_auth: ^3.4.2
  cached_network_image: ^3.2.1
  flutter_slidable: ^2.0.0
  share_plus: ^4.0.10
  quick_actions: ^0.6.0+11
  wakelock: ^0.6.2
  new_version: ^0.3.1
  flutter_carousel_widget: ^1.1.0
  google_sign_in: ^5.4.0
  simple_connection_checker: ^0.2.1
  intl_phone_field: ^3.1.0
  firebase_crashlytics: ^2.8.5
  flutter_windowmanager: ^0.2.0
  alh_pdf_view: ^0.3.3
  firebase_app_check: ^0.0.6+17
  app_settings: ^4.1.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 

  uses-material-design: true

  assets:
    - assets/
    - .env.production
    - .env.development
    - .env.staging