name: filegram
version: 1.1.4+32
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^1.0.5
  flutter_dotenv: ^5.0.2
  flutter_file_dialog: ^2.3.0
  flutter_native_splash: ^1.3.3
  flutter_pdfview_professor: ^1.0.1
  flutter_slidable: ^1.2.0
  flutter_windowmanager: ^0.2.0
  get: ^4.6.1
  get_storage: ^2.0.3
  google_mobile_ads: ^1.0.1
  google_sign_in: ^5.2.2
  in_app_update: ^3.0.0
  intl_phone_field: ^3.1.0
  lottie: ^1.2.1
  open_as_default: ^0.0.3
  path_provider: ^2.0.8
  receive_sharing_intent: ^1.4.5
  share_plus: ^3.0.4
  simple_connection_checker: ^0.2.1
  url_launcher: ^6.0.20

dev_dependencies:
  build_runner: ^2.1.7
  envify_generator: ^2.0.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#000000"
  #background_image: "assets/protect.png"
  image: assets/filegram_splash.png
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/google.json
    - assets/loading.json
    - assets/empty.json
    - assets/error.json
    - assets/no_internet.json
    - assets/app_bar.png
    - assets/encryption.json
    - assets/no_cloud.json
    - assets/pocket_pdf.json
    - assets/whatsapp.json
    - .env.production
    - .env.development
    - .env.staging
