name: flutter_build_development

on: push

jobs:
  build:
    name: Flutter Build Development (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: FLUTTER PUB GET    
        run: flutter pub get

      - name: FLUTTER CLEAN
        run: flutter clean

      - name: FLUTTER DEVELOPEMENT BUILD BUNDLE
        run: flutter build appbundle --debug –flavor development -t lib/main_development.dart
