name: flutter_build_production

on: 
  push:
    tags:
      - "v*" 

jobs:
  build:
    name: Flutter Build Production (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Decoding android/key.properties
        run: echo "${{ secrets.KEY_PROD }}" | base64 --decode > android/key.properties

      - name: Decoding android/keystore.jks
        run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Decoding firebase google-services.json
        run: echo "${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json  

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"  

      - name: FLUTTER PUB GET    
        run: flutter pub get

      - name: FLUTTER CLEAN
        run: flutter clean

      - name: Build APK
        run: flutter build apk --split-per-abi --flavor production -t lib/main_production.dart  
        
      - name: FLUTTER PRODUCTION BUILD BUNDLE
        run: flutter build appbundle --flavor production -t lib/main_production.dart

      - name: Create github artifact release # disable this to save storage
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/release/*.apk,build/app/outputs/bundle/productionRelease/*.aab"
          token: ${{secrets.TOKEN}} # this is automatically provided by github
  
