name: flutter_run

on: push

jobs:
  build:
    name: Flutter Run (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: FLUTTER PUB GET    
      - run: flutter pub get

      - name: FLUTTER CLEAN
      - run: flutter clean

      - name: FLUTTER DEVELOPMENT RUN 
      - run: flutter run –flavor development -t lib/main_development.dart