name: flutter_build_development

on: push


jobs:
  build:
    name: Flutter Build Production (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: FLUTTER PUB GET    
        run: flutter pub get

      - name: FLUTTER CLEAN
        run: flutter clean

      - name: Build APK
        run: flutter build apk --debug --split-per-abi --flavor development -t lib/main_development.dart  
        
      - name: FLUTTER PRODUCTION BUILD BUNDLE
        run: flutter build appbundle --debug --flavor development -t lib/main_development.dart
  
      - name: Upload app bundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: appbundle
          path: build/app/outputs/bundle/debug/app-debug.aab  
